from __future__ import annotations

from datetime import datetime
from typing import Iterable, List, Optional, Protocol, Sequence

from .models import (
    ArtifactMetadata,
    Candidate,
    CheckpointMetadata,
    EvaluationResult,
    EvaluationJob,
    Event,
    OptimizationTask,
    Run,
    AgentMemory,
    ToolCallRecord,
)


class CandidateEvaluator(Protocol):
    def evaluate(self, candidate: Candidate, task: OptimizationTask) -> EvaluationResult:
        ...


class CandidateProposal(Protocol):
    code: str
    description: str
    operators: List[str]


class LLMPort(Protocol):
    def generate_candidate(
        self,
        operator: str,
        parents: Sequence[Candidate],
        generation: int,
        agent_context: str = "",
    ) -> CandidateProposal:
        ...


class RuntimeStore(Protocol):
    def create_task_run(self, task: OptimizationTask, run: Run, event_type: str,
                        message: str, payload: dict) -> Event: ...
    def add_task(self, task: OptimizationTask) -> None: ...
    def add_run(self, run: Run) -> None: ...
    def get_task(self, task_id: str) -> OptimizationTask: ...
    def get_run(self, run_id: str) -> Run: ...
    def start_run(self, run_id: str, expected_status, now: datetime,
                  owner_id: str = "") -> Run: ...
    def pause_run(self, run_id: str, owner_id: str, now: datetime) -> Run: ...
    def complete_run(self, run_id: str, owner_id: str, now: datetime,
                     generation: int, best_candidate_id: str) -> Run: ...
    def fail_run(self, run_id: str, reason: str, now: datetime,
                 owner_id: str = "") -> Run: ...
    def update_run_progress(self, run_id: str, owner_id: str, now: datetime,
                            generation: int) -> Run: ...
    def save_run(self, run: Run) -> None: ...
    def request_run_pause(self, run_id: str, reason: str) -> Run: ...
    def request_run_cancel(self, run_id: str, reason: str) -> Run: ...
    def claim_run_lease(self, run_id: str, owner_id: str, now: datetime,
                        lease_seconds: int) -> bool: ...
    def renew_run_lease(self, run_id: str, owner_id: str, now: datetime,
                        lease_seconds: int) -> bool: ...
    def release_run_lease(self, run_id: str, owner_id: str) -> bool: ...
    def update_runtime_cursor(self, run_id: str, artifact_id: str,
                              owner_id: str = "",
                              now: Optional[datetime] = None) -> bool: ...
    def add_candidate(self, candidate: Candidate) -> None: ...
    def candidates_for_run(self, run_id: str) -> Iterable[Candidate]: ...
    def candidate_by_id(self, candidate_id: str) -> Candidate: ...
    def add_result(self, result: EvaluationResult) -> None: ...
    def result_for_candidate(self, candidate_id: str) -> EvaluationResult: ...
    def append_event(self, run_id: str, event_type: str, message: str, **payload: object) -> Event: ...
    def events_for_run(self, run_id: str) -> Iterable[Event]: ...
    def put_artifact(self, run_id: str, kind: str, content: bytes, media_type: str) -> ArtifactMetadata: ...
    def artifact_content(self, artifact_id: str) -> bytes: ...
    def artifacts_for_run(self, run_id: str) -> Iterable[ArtifactMetadata]: ...
    def add_checkpoint(self, checkpoint: CheckpointMetadata) -> None: ...
    def latest_checkpoint(self, run_id: str) -> CheckpointMetadata: ...
    def add_agent_memory(self, memory: AgentMemory) -> None: ...
    def add_agent_task(self, task) -> tuple: ...
    def get_agent_task(self, task_id: str): ...
    def agent_tasks_for_run(self, run_id: str): ...
    def claim_agent_task(self, task_id: str, agent_name: str,
                         now: Optional[datetime] = None,
                         lease_seconds: int = 300,
                         claim_token: str = ""): ...
    def renew_agent_task_lease(self, task_id: str, claim_token: str,
                               now: datetime, lease_seconds: int) -> bool: ...
    def complete_agent_task(self, task_id: str, claim_token: str,
                            output_artifact_refs,
                            now: Optional[datetime] = None): ...
    def fail_agent_task(self, task_id: str, claim_token: str,
                        error_message: str,
                        now: Optional[datetime] = None): ...
    def agent_memories_for_dataset(self, dataset_id: str, limit: int = 5,
                                   exclude_run_id: str = "") -> Iterable[AgentMemory]: ...
    def agent_memories_for_run(self, run_id: str, scope: str,
                               limit: int = 30) -> Iterable[AgentMemory]: ...
    def record_tool_call(self, record: ToolCallRecord) -> None: ...
    def tool_calls_for_run(self, run_id: str) -> Iterable[ToolCallRecord]: ...


class EvaluationQueueStore(Protocol):
    def enqueue_job(self, job: EvaluationJob) -> tuple: ...
    def claim_next_job(self, worker_id: str, now: datetime, lease_seconds: int) -> Optional[EvaluationJob]: ...
    def renew_job_lease(self, job_id: str, worker_id: str, now: datetime,
                        lease_seconds: int) -> bool: ...
    def complete_job_success(self, job_id: str, worker_id: str,
                             result: EvaluationResult,
                             artifact_id: str,
                             now: datetime) -> EvaluationJob: ...
    def complete_job_failure(self, job_id: str, worker_id: str,
                             error_code: str, message: str, retryable: bool,
                             available_at: datetime,
                             now: datetime) -> EvaluationJob: ...
    def recover_stale_jobs(self, now: datetime, run_id: str = "") -> int: ...
    def get_evaluation_job(self, job_id: str) -> EvaluationJob: ...
    def evaluation_jobs_for_run(self, run_id: str) -> Iterable[EvaluationJob]: ...
    def result_for_candidate(self, candidate_id: str) -> EvaluationResult: ...
    def get_task(self, task_id: str) -> OptimizationTask: ...
    def get_run(self, run_id: str) -> Run: ...
    def candidate_by_id(self, candidate_id: str) -> Candidate: ...
    def put_artifact(self, run_id: str, kind: str, content: bytes, media_type: str) -> ArtifactMetadata: ...
    def append_event(self, run_id: str, event_type: str, message: str, **payload: object) -> Event: ...
